/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FilmRouteImport } from './routes/film'
import { Route as DiscussionRouteImport } from './routes/discussion'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmIdRouteImport } from './routes/film.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionRoute = DiscussionRouteImport.update({
  id: '/discussion',
  path: '/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FilmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discussion': typeof DiscussionRoute
  '/film': typeof FilmRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/film/$id': typeof FilmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discussion': typeof DiscussionRoute
  '/film': typeof FilmRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/film/$id': typeof FilmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discussion': typeof DiscussionRoute
  '/film': typeof FilmRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/film/$id': typeof FilmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/discussion'
    | '/film'
    | '/help'
    | '/login'
    | '/signup'
    | '/film/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/discussion'
    | '/film'
    | '/help'
    | '/login'
    | '/signup'
    | '/film/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/discussion'
    | '/film'
    | '/help'
    | '/login'
    | '/signup'
    | '/film/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DiscussionRoute: typeof DiscussionRoute
  FilmRoute: typeof FilmRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussion': {
      id: '/discussion'
      path: '/discussion'
      fullPath: '/discussion'
      preLoaderRoute: typeof DiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof FilmRoute
    }
  }
}

interface FilmRouteChildren {
  FilmIdRoute: typeof FilmIdRoute
}

const FilmRouteChildren: FilmRouteChildren = {
  FilmIdRoute: FilmIdRoute,
}

const FilmRouteWithChildren = FilmRoute._addFileChildren(FilmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DiscussionRoute: DiscussionRoute,
  FilmRoute: FilmRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
